// source: js_event.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.wow.web.proto.JsEvent');
goog.provide('proto.wow.web.proto.JsEvent.EventCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.wow.web.proto.BrowseFolderRequest');
goog.require('proto.wow.web.proto.BrowseFolderResponse');
goog.require('proto.wow.web.proto.InitializeRequest');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.wow.web.proto.JsEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.wow.web.proto.JsEvent.oneofGroups_);
};
goog.inherits(proto.wow.web.proto.JsEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.wow.web.proto.JsEvent.displayName = 'proto.wow.web.proto.JsEvent';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.wow.web.proto.JsEvent.oneofGroups_ = [[1,10,20]];

/**
 * @enum {number}
 */
proto.wow.web.proto.JsEvent.EventCase = {
  EVENT_NOT_SET: 0,
  INITIALIZE_REQUEST: 1,
  BROWSE_FOLDER_REQUEST: 10,
  BROWSE_FOLDER_RESPONSE: 20
};

/**
 * @return {proto.wow.web.proto.JsEvent.EventCase}
 */
proto.wow.web.proto.JsEvent.prototype.getEventCase = function() {
  return /** @type {proto.wow.web.proto.JsEvent.EventCase} */(jspb.Message.computeOneofCase(this, proto.wow.web.proto.JsEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.wow.web.proto.JsEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.wow.web.proto.JsEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.wow.web.proto.JsEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wow.web.proto.JsEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
initializeRequest: (f = msg.getInitializeRequest()) && proto.wow.web.proto.InitializeRequest.toObject(includeInstance, f),
browseFolderRequest: (f = msg.getBrowseFolderRequest()) && proto.wow.web.proto.BrowseFolderRequest.toObject(includeInstance, f),
browseFolderResponse: (f = msg.getBrowseFolderResponse()) && proto.wow.web.proto.BrowseFolderResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.wow.web.proto.JsEvent}
 */
proto.wow.web.proto.JsEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.wow.web.proto.JsEvent;
  return proto.wow.web.proto.JsEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.wow.web.proto.JsEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.wow.web.proto.JsEvent}
 */
proto.wow.web.proto.JsEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.wow.web.proto.InitializeRequest;
      reader.readMessage(value,proto.wow.web.proto.InitializeRequest.deserializeBinaryFromReader);
      msg.setInitializeRequest(value);
      break;
    case 10:
      var value = new proto.wow.web.proto.BrowseFolderRequest;
      reader.readMessage(value,proto.wow.web.proto.BrowseFolderRequest.deserializeBinaryFromReader);
      msg.setBrowseFolderRequest(value);
      break;
    case 20:
      var value = new proto.wow.web.proto.BrowseFolderResponse;
      reader.readMessage(value,proto.wow.web.proto.BrowseFolderResponse.deserializeBinaryFromReader);
      msg.setBrowseFolderResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.wow.web.proto.JsEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.wow.web.proto.JsEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.wow.web.proto.JsEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.wow.web.proto.JsEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitializeRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.wow.web.proto.InitializeRequest.serializeBinaryToWriter
    );
  }
  f = message.getBrowseFolderRequest();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.wow.web.proto.BrowseFolderRequest.serializeBinaryToWriter
    );
  }
  f = message.getBrowseFolderResponse();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      proto.wow.web.proto.BrowseFolderResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional InitializeRequest initialize_request = 1;
 * @return {?proto.wow.web.proto.InitializeRequest}
 */
proto.wow.web.proto.JsEvent.prototype.getInitializeRequest = function() {
  return /** @type{?proto.wow.web.proto.InitializeRequest} */ (
    jspb.Message.getWrapperField(this, proto.wow.web.proto.InitializeRequest, 1));
};


/**
 * @param {?proto.wow.web.proto.InitializeRequest|undefined} value
 * @return {!proto.wow.web.proto.JsEvent} returns this
*/
proto.wow.web.proto.JsEvent.prototype.setInitializeRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.wow.web.proto.JsEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wow.web.proto.JsEvent} returns this
 */
proto.wow.web.proto.JsEvent.prototype.clearInitializeRequest = function() {
  return this.setInitializeRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wow.web.proto.JsEvent.prototype.hasInitializeRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BrowseFolderRequest browse_folder_request = 10;
 * @return {?proto.wow.web.proto.BrowseFolderRequest}
 */
proto.wow.web.proto.JsEvent.prototype.getBrowseFolderRequest = function() {
  return /** @type{?proto.wow.web.proto.BrowseFolderRequest} */ (
    jspb.Message.getWrapperField(this, proto.wow.web.proto.BrowseFolderRequest, 10));
};


/**
 * @param {?proto.wow.web.proto.BrowseFolderRequest|undefined} value
 * @return {!proto.wow.web.proto.JsEvent} returns this
*/
proto.wow.web.proto.JsEvent.prototype.setBrowseFolderRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.wow.web.proto.JsEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wow.web.proto.JsEvent} returns this
 */
proto.wow.web.proto.JsEvent.prototype.clearBrowseFolderRequest = function() {
  return this.setBrowseFolderRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wow.web.proto.JsEvent.prototype.hasBrowseFolderRequest = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional BrowseFolderResponse browse_folder_response = 20;
 * @return {?proto.wow.web.proto.BrowseFolderResponse}
 */
proto.wow.web.proto.JsEvent.prototype.getBrowseFolderResponse = function() {
  return /** @type{?proto.wow.web.proto.BrowseFolderResponse} */ (
    jspb.Message.getWrapperField(this, proto.wow.web.proto.BrowseFolderResponse, 20));
};


/**
 * @param {?proto.wow.web.proto.BrowseFolderResponse|undefined} value
 * @return {!proto.wow.web.proto.JsEvent} returns this
*/
proto.wow.web.proto.JsEvent.prototype.setBrowseFolderResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 20, proto.wow.web.proto.JsEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.wow.web.proto.JsEvent} returns this
 */
proto.wow.web.proto.JsEvent.prototype.clearBrowseFolderResponse = function() {
  return this.setBrowseFolderResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.wow.web.proto.JsEvent.prototype.hasBrowseFolderResponse = function() {
  return jspb.Message.getField(this, 20) != null;
};


